name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Navigate to directory containing Dockerfile
        run: cd node-terraform/app

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up QEMU for arm64
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        if: runner.os == 'Linux'

      - name: Set up Docker for arm64
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3


      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 975049941899.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build -t newrepo .
          docker tag my-repository:latest 975049941899.dkr.ecr.us-east-1.amazonaws.com/my-repository:latest
          docker push 975049941899.dkr.ecr.us-east-1.amazonaws.com/my-repository:latest

      - name: Deploy to ECS Fargate
        run: |
          aws ecs update-service --cluster my-cluster --service public-ecs-service" --force-new-deployment